export const styles = {
  page: { minHeight: "100vh", background: "linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Segoe UI', sans-serif", padding: 16 },
  landingWrap: { background: "rgba(255,255,255,0.04)", backdropFilter: "blur(20px)", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 20, padding: "40px 32px", width: "100%", maxWidth: 440, textAlign: "center" },
  logo: { display: "flex", alignItems: "center", justifyContent: "center", gap: 10, marginBottom: 4 },
  logoIcon: { fontSize: 32, color: "#38bdf8" },
  logoText: { fontSize: 28, fontWeight: 800, color: "#fff", letterSpacing: -1 },
  tagline: { color: "#94a3b8", marginBottom: 32, fontSize: 14 },
  roleCards: { display: "flex", gap: 16 },
  roleCard: { flex: 1, border: "none", borderRadius: 14, padding: "20px 12px", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, transition: "transform 0.15s" },
  adminCard: { background: "linear-gradient(135deg, #1e40af, #3b82f6)" },
  empCard: { background: "linear-gradient(135deg, #065f46, #10b981)" },
  roleIcon: { fontSize: 28 },
  roleLabel: { color: "#fff", fontWeight: 700, fontSize: 15 },
  roleDesc: { color: "rgba(255,255,255,0.7)", fontSize: 12 },
  loginBox: { textAlign: "left" },
  loginTitle: { color: "#fff", marginBottom: 20, textAlign: "center" },
  input: { width: "100%", padding: "10px 14px", borderRadius: 8, border: "1px solid rgba(255,255,255,0.15)", background: "rgba(255,255,255,0.07)", color: "#fff", fontSize: 14, marginBottom: 12, boxSizing: "border-box", outline: "none" },
  btnPrimary: { width: "100%", padding: "12px", borderRadius: 8, border: "none", background: "linear-gradient(135deg, #3b82f6, #2563eb)", color: "#fff", fontWeight: 700, fontSize: 15, cursor: "pointer", marginBottom: 8 },
  btnGhost: { width: "100%", padding: "10px", borderRadius: 8, border: "1px solid rgba(255,255,255,0.2)", background: "transparent", color: "#94a3b8", fontSize: 14, cursor: "pointer", marginBottom: 4 },
  error: { color: "#f87171", fontSize: 13, marginBottom: 8 },
  appWrap: { minHeight: "100vh", background: "#0f172a", fontFamily: "'Segoe UI', sans-serif", color: "#e2e8f0" },
  header: { background: "#1e293b", padding: "12px 20px", display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "1px solid #334155" },
  headerLeft: { display: "flex", alignItems: "center", gap: 12 },
  logoSmall: { fontSize: 18, fontWeight: 800, color: "#38bdf8" },
  adminBadge: { background: "#1e40af", color: "#93c5fd", padding: "3px 10px", borderRadius: 20, fontSize: 12, fontWeight: 600 },
  logoutBtn: { background: "transparent", border: "1px solid #475569", color: "#94a3b8", padding: "6px 14px", borderRadius: 6, cursor: "pointer", fontSize: 13 },
  nav: { background: "#1e293b", padding: "0 16px", display: "flex", gap: 4, borderBottom: "1px solid #334155", overflowX: "auto" },
  navBtn: { background: "transparent", border: "none", color: "#94a3b8", padding: "12px 14px", cursor: "pointer", fontSize: 13, whiteSpace: "nowrap", borderBottom: "2px solid transparent" },
  navBtnActive: { color: "#38bdf8", borderBottom: "2px solid #38bdf8" },
  content: { padding: "24px 20px", maxWidth: 900, margin: "0 auto" },
  sectionTitle: { fontSize: 18, fontWeight: 700, color: "#f1f5f9", marginBottom: 16, marginTop: 0 },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: 12, marginBottom: 24 },
  statCard: { background: "#1e293b", borderRadius: 10, padding: "14px 16px", display: "flex", alignItems: "center", gap: 12 },
  statIcon: { fontSize: 24 },
  statValue: { fontSize: 22, fontWeight: 800, color: "#f1f5f9" },
  statLabel: { fontSize: 11, color: "#94a3b8", fontWeight: 500, marginTop: 2 },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: { background: "#1e293b", padding: "10px 12px", textAlign: "left", color: "#64748b", fontWeight: 600, fontSize: 12 },
  tr: { borderBottom: "1px solid #1e293b" },
  td: { padding: "10px 12px", color: "#e2e8f0" },
  badge: { padding: "2px 10px", borderRadius: 20, fontSize: 11, fontWeight: 600 },
  empty: { color: "#475569", textAlign: "center", padding: "40px 0", fontSize: 14 },
  rowBetween: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  modal: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 16 },
  modalBox: { background: "#1e293b", borderRadius: 14, padding: 24, width: "100%", maxWidth: 400, maxHeight: "90vh", overflowY: "auto" },
  modalTitle: { fontSize: 18, fontWeight: 700, marginBottom: 16, color: "#f1f5f9" },
  modalBtns: { display: "flex", gap: 10, marginTop: 16 },
  label: { fontSize: 12, color: "#94a3b8", fontWeight: 600, display: "block", marginBottom: 4 },
  photoWrap: { display: "flex", flexDirection: "column", alignItems: "center", gap: 8, marginBottom: 16 },
  empPhoto: { width: 80, height: 80, borderRadius: "50%", objectFit: "cover" },
  empPhotoEmpty: { width: 80, height: 80, borderRadius: "50%", background: "#334155", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28 },
  empGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 14 },
  empCard: { background: "#1e293b", borderRadius: 12, padding: 16, display: "flex", alignItems: "center", gap: 12 },
  empCardPhoto: { width: 52, height: 52, borderRadius: "50%", objectFit: "cover", flexShrink: 0 },
  empCardPhotoEmpty: { width: 52, height: 52, borderRadius: "50%", background: "#334155", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, flexShrink: 0 },
  empCardInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 2 },
  empName: { color: "#f1f5f9", fontSize: 14 },
  empDetail: { color: "#64748b", fontSize: 12 },
  empCardActions: { display: "flex", flexDirection: "column", gap: 4 },
  btnSm: { padding: "5px 10px", borderRadius: 6, border: "none", background: "#334155", color: "#e2e8f0", cursor: "pointer", fontSize: 13 },
  filters: { display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap" },
  cameraWrap: { width: "100%", maxWidth: 400, margin: "0 auto 12px", background: "#1e293b", borderRadius: 12, overflow: "hidden", aspectRatio: "4/3", display: "flex", alignItems: "center", justifyContent: "center" },
  video: { width: "100%", borderRadius: 12 },
  cameraPlaceholder: { color: "#475569", fontSize: 32, textAlign: "center" },
  cameraControls: { display: "flex", gap: 10, justifyContent: "center", marginBottom: 16 },
  empSelect: { display: "flex", flexDirection: "column", gap: 10, maxWidth: 400, margin: "0 auto" },
  msgBox: { background: "#1e3a5f", border: "1px solid #3b82f6", borderRadius: 8, padding: "10px 14px", color: "#93c5fd", marginTop: 8, fontSize: 14 },
  note: { background: "#1e293b", borderRadius: 8, padding: "10px 14px", color: "#64748b", fontSize: 13, marginBottom: 16 },
  settingsBox: { background: "#1e293b", borderRadius: 12, padding: 24, maxWidth: 360 },
  empProfile: { display: "flex", gap: 20, alignItems: "center", background: "#1e293b", borderRadius: 14, padding: 20, marginBottom: 24 },
  profilePhoto: { width: 80, height: 80, borderRadius: "50%", objectFit: "cover" },
  profilePhotoEmpty: { width: 80, height: 80, borderRadius: "50%", background: "#334155", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 36 },
  profileName: { fontSize: 22, fontWeight: 800, color: "#f1f5f9", margin: "0 0 4px" },
  profileRole: { color: "#38bdf8", fontSize: 14, margin: 0 },
  todayBox: { background: "#1e293b", borderRadius: 14, padding: 20, marginBottom: 24 },
  checkinRow: { display: "flex", gap: 24, marginBottom: 16 },
  checkinInfo: { display: "flex", flexDirection: "column", gap: 4 },
  checkinBtns: { display: "flex", gap: 10, marginBottom: 8 },
};
